const permissions = [
  'CEO',
  'VIEW_PROJECTS',
  'ADD_PROJECT',
  'EDIT_PROJECT',
  'SUPER_USER',
  'SET_ROLES',
  'MANUAL_ACTIVATE',
  'SEE_USERS_LIST',
  'DELETE_USER',
  'EDIT_SELF',
  'SET_AVAILABILITY',
  'GET_LISTING',
  'GET_ALL_LISTING',
  'ADD_LISTING',
  'EDIT_LISTING',
  'DELETE_LISTING',
  'ADD_ORDER',
  'VIEW_ORDER',
  'CHANGE_ORDER_STATUS',
  'SET_ORDER_REVIEW',
  'ADD_CATEGORY',
  'EDIT_CATEGORY',
  'DELETE CATEGORY',
  'CHAT'
];

module.exports = permissions;